- name: This playbook will install, configure and deploy web pages into nginx
  hosts: all
  become: yes
  tasks:
   - name: Install nginx web server
     apt: name=nginx state=latest update_cache=yes

   - name: Start the Webserver
     #service: name=nginx state=started enabled=yes
     command: service nginx start 
